### ISSUE TITLE
Double cannot cast to string

### ISSUE THREAD

**Issue by tarunkonda123** [LukeBrandonFarrell/react-native-images-collage#2]
import React, { Component } from "react";
import { View, Text, Dimensions,Image } from "react-native";
import PropTypes from "prop-types";
import { connect } from "react-redux";
import { DynamicCollage, StaticCollage } from "react-native-images-collage";

import image1 from "../images/ic_launcher.png";
import image2 from "../images/ic_launcher.png";

export class Fifth extends Component {
  constructor(props) {
    super(props);
    this.state = { photos: [image1, image2] };
  }

  render() {
    return (
      <DynamicCollage
        width={Dimensions.get("window").width / 1.1}
        height={Dimensions.get("window").width / 1.1}
        images={this.state.photos}
        matrix={[1, 1]}
      />
    );
  }
}

const mapStateToProps = state => ({});

const mapDispatchToProps = {};

export default connect(mapStateToProps, mapDispatchToProps)(Fifth);

**Comment by LukeBrandonFarrell** [comment]
@tarunkonda123 @akinolu52 

Thanks for flagging this. I'll look into this over the next few days, publish a fix, and let you know.

**Comment by akinolu52** [comment]
ok @LukeBrandonFarrell  i'll be waiting

**Comment by LukeBrandonFarrell** [comment]
@tarunkonda123 @akinolu52 This error occurs due to the way the library uses images. The dynamic component needs to load the resource via a URLReqeust in order to get the image dimensions for user interaction.

`
<Image source={{ uri: image.url }} ...
`


You must pass your images as URIs

URL: `http://example/image.png`
Image on file system: `file://...example/image.png`

**At the moment, in order to use the dynamic collage with local (static) images you must first save them to the users filesystem temporarily and pass the URIs to the component.**

Albeit, it would be possible to detect if the image is static or dynamic and then use [resolveAssetSource](https://github.com/facebook/react-native/blob/master/Libraries/Image/resolveAssetSource.js) to get the dimensions of the static image. This would allow us to use `require()` or `import`. 

Although, it would be tricky to implement. If one of you wants to make the first attempt and PR, I'd be willing to help code this.

**Comment by akinolu52** [comment]
thanks @LukeBrandonFarrell
